### ISSUE TITLE
License

### ISSUE THREAD

**Issue by moxvallix** [ssarmis/copper_ore#1]
I’m interested in using this project as a base for a skin editor I’m working on, just curious of what the license for it is?

If you are open to releasing it as MIT or GPL3 that’d be awesome.

**Comment by ssarmis** [comment]
Hi, feel free to use it, currently I don't have access to a pc, will update the license soon

**Comment by ssarmis** [comment]
I added an MIT license, good luck on your project!

**Comment by moxvallix** [comment]
Sweet thank you so much :)
